# Site settings
title: Joe Zeng
description: 'Software and Sports' # write a nice description for your blog
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://blog.joezeng.me' # the base hostname & protocol for your site http://www.example.com

# Build settings
markdown: kramdown

permalink: '/:title/'

gems: [jekyll-paginate]

paginate: 10
